lsi: false
safe: true
source: src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "main"