name: Eleventy Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build:gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
